CREATE TABLE `TRANSACTION_TABLE` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`TRANS_ID` VARCHAR(255) NOT NULL,
	`USER_ID` INT NOT NULL,
	`ITEM_ID` INT NOT NULL,
	`QUANTITY` INT NOT NULL,
	`RETURN_DATE` DATE NOT NULL,
	`TRANS_TYPE` ENUM("'borrow'", "'return'", "'late'", "'lost'") NOT NULL DEFAULT 'borrow',
	`CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`CID` VARCHAR(255) NOT NULL,
	`MTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`MID` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `USER_TABLE` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`USR_ID` VARCHAR(255) NOT NULL,
	`DETAIL_ID` INT NOT NULL,
	`LOGIN_ID` INT NOT NULL,
	`COURSE` VARCHAR(255) NOT NULL,
	`CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`CID` VARCHAR(255) NOT NULL,
	`MTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`MID` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `DETAIL_TABLE` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`FIRST_NAME` VARCHAR(255) NOT NULL,
	`MIDDLE_NAME` VARCHAR(255) NOT NULL,
	`LAST_NAME` VARCHAR(255) NOT NULL,
	`EMAIL_ADDRESS` VARCHAR(255) NOT NULL,
	`PHONE_NUMBER` VARCHAR(13) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `ITEM_TABLE` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`ITM_ID` VARCHAR(255) NOT NULL,
	`CTY_ID` INT NOT NULL,
	`ITEM_NAME` VARCHAR(255) NOT NULL,
	`TOTAL_COUNT` INT NOT NULL,
	`BASE_COUNT` INT NOT NULL,
	`CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`CID` VARCHAR(255) NOT NULL,
	`MTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`MID` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `LOGIN_TABLE` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`USERNAME` VARCHAR(255) NOT NULL,
	`PASSWORD` VARCHAR(255) NOT NULL,
	`RECOVERY_CODE` VARCHAR(255) NOT NULL,
	`CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`CID` VARCHAR(255) NOT NULL,
	`MTIME` TIMESTAMP NOT NULL,
	`MID` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `ADMIN_TABLE` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`ADM_ID` VARCHAR(255) NOT NULL,
	`DETAIL_ID` INT NOT NULL,
	`LOGIN_ID` INT NOT NULL,
	`ADM_ROLE` ENUM("ADMIN", "SUPER", "SUB") NOT NULL DEFAULT 'SUB',
	`CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`CID` VARCHAR(255) NOT NULL,
	`MTIME` VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`MID` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `REPORT_TABLE` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`REPT_ID` VARCHAR(255) NOT NULL,
	`ITEM_ID` INT NOT NULL,
	`USER_ID` INT NOT NULL,
	`REPT_TYPE` ENUM("LOST", "DAMAGED") NOT NULL,
	`CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`CID` VARCHAR(255) NOT NULL,
	`MTIME` VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`MID` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);

CREATE TABLE `CATEGORY_TABLE` (
	`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`C_NAME` VARCHAR(255) NOT NULL,
	`CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`CID` VARCHAR(255) NOT NULL,
	`MTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	`MID` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ID`)
);

ALTER TABLE `ITEM_TABLE`
ADD FOREIGN KEY(`ID`) REFERENCES `TRANSACTION_TABLE`(`ITEM_ID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `USER_TABLE`
ADD FOREIGN KEY(`ID`) REFERENCES `TRANSACTION_TABLE`(`USER_ID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `DETAIL_TABLE`
ADD FOREIGN KEY(`ID`) REFERENCES `USER_TABLE`(`DETAIL_ID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `LOGIN_TABLE`
ADD FOREIGN KEY(`ID`) REFERENCES `USER_TABLE`(`LOGIN_ID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `DETAIL_TABLE`
ADD FOREIGN KEY(`ID`) REFERENCES `ADMIN_TABLE`(`DETAIL_ID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `LOGIN_TABLE`
ADD FOREIGN KEY(`ID`) REFERENCES `ADMIN_TABLE`(`LOGIN_ID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `ITEM_TABLE`
ADD FOREIGN KEY(`CTY_ID`) REFERENCES `CATEGORY_TABLE`(`ID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `ITEM_TABLE`
ADD FOREIGN KEY(`ID`) REFERENCES `REPORT_TABLE`(`ITEM_ID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `USER_TABLE`
ADD FOREIGN KEY(`ID`) REFERENCES `REPORT_TABLE`(`USER_ID`)
ON UPDATE NO ACTION ON DELETE CASCADE;